# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      CC: aarch64-linux-gnu-gcc
      CXX: aarch64-linux-gnu-g++
      LD: aarch64-linux-gnu-ld
      AR: aarch64-linux-gnu-ar

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: checkout
        run: git clone http://thekelleys.org.uk/git/dnsmasq.git dnsmasq.git
      - name: prepare
        run: sudo apt update && sudo apt install gcc-aarch64-linux-gnu
      - name: patching
        run: |
             cd dnsmasq.git 
             sed -i '/#include "dnsmasq.h"/a __asm__(".symver fcntl64,fcntl@GLIBC_2.17");' src/network.c
             sed -i '/#include "dnsmasq.h"/a __asm__(".symver fcntl64,fcntl@GLIBC_2.17");' src/netlink.c
             sed -i '/#include "dnsmasq.h"/a __asm__(".symver fcntl64,fcntl@GLIBC_2.17");' src/dnsmasq.c
             sed -i '/#include "dnsmasq.h"/a __asm__(".symver fcntl64,fcntl@GLIBC_2.17");' src/helper.c
             cd ..

      # Runs a set of commands using the runners shell
      - name: build
        run: cd dnsmasq.git &&make COPTS="-DHAVE_IPSET -DHAVE_BROKEN_RTC -DNO_AUTH -DNO_INOTIFY -DNO_DUMPFILE -DNO_LOOP" && aarch64-linux-gnu-strip -s -x src/dnsmasq &&cp src/dnsmasq ../dnsmasq && cp CHANGELOG  ../CHANGELOG
        
      - name: dist
        run: git status &&git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com" &&  git config --local user.name "github-actions[bot]" &&git add dnsmasq CHANGELOG &&git commit -m "update by bot"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
 #
