# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  workflow_dispatch:
  schedule:
    - cron: "1 1 */7 * *"
#   create:
#     tags:
#       - v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
#     strategy:
#       matrix:
#         include:
#           - arch: aarch64
#             distro: ubuntu18.04
    env:
      CC: aarch64-linux-gnu-gcc
      CXX: aarch64-linux-gnu-g++
      LD: aarch64-linux-gnu-ld
      AR: aarch64-linux-gnu-ar

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
         ref: master

      # Runs a single command using the runners shell
      - name: checkoutDnsmasq
        run: git clone http://thekelleys.org.uk/git/dnsmasq.git dnsmasq.git
      - name: checkoutHttping
        run: git clone https://github.com/folkertvanheusden/HTTPing httping.git
        
      - name: prepare
        run: sudo apt update && sudo apt install gcc-aarch64-linux-gnu texlive  libgmp-dev gettext autoconf pkg-config
      - name: patching 
        run: |
             cd dnsmasq.git 

             sed -i '/#include <sys\/stat.h>/a __asm__(".symver stat64,__xstat64@GLIBC_2.17");' src/dnsmasq.h
             sed -i '/#include <fcntl.h>/a __asm__(".symver fcntl64,fcntl@GLIBC_2.17");' src/dnsmasq.h
             sed -i '/#include <fcntl.h>/a __asm__(".symver fcntl64,fcntl@GLIBC_2.17");' src/tables.c
       
             cd ..
             
      - name: patching-httping
        run: |
             cp httpmake httping.git/Makefile 

 
      # Runs a set of commands using the runners shell
      - name: loadFile
        run:  unzip nettle_3.9.1.zip && cd nettle_3.9.1 &&./.bootstrap && ./configure --enable-mini-gmp --disable-documentation --host=aarch64-linux-gnu &&make &&sudo make install && cd ..
      - name: build
        run: chmod +x build.sh &&./build.sh
      - name: buildHttping
        run:  cp httping.config httping.git/config.h &&cd httping.git &&make && aarch64-linux-gnu-strip -s -x httping &&cp httping ../httping 
        
      - name: dist
        run: git status &&git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com" &&  git config --local user.name "github-actions[bot]" &&git add dnsmasq CHANGELOG httping &&git commit -m "update by bot"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
 #
